### ISSUE TITLE
Pre-compiled Release Binary

### ISSUE THREAD

**Issue by weslambert** [M00NLIG7/ChopChopGo#1]
Thanks for all of the work that went into making this possible!

Would it be possible to host a pre-compiled binary and associated rule files in a ZIP file, so that user's don't have to compile it themselves?

**Comment by M00NLIG7** [comment]
Yes I can get that set up right away!
> Thanks for all of the work that went into making this possible!
> 
> 
> 
> Would it be possible to host a pre-compiled binary and associated rule files in a ZIP file, so that user's don't have to compile it themselves?

**Comment by M00NLIG7** [comment]
The Pre-compiled binary has been added to release.

**Comment by weslambert** [comment]
Thank you!
