### ISSUE TITLE
go build issue when attempting to compile for windows

### ISSUE THREAD

**Issue by reece394** [M00NLIG7/ChopChopGo#11]
When I attempt to build ChopChopGo for windows I get the following error: 

`github.com/coreos/go-systemd/v22/internal/dlopen: build constraints exclude all Go files in C:\Users\user\go\pkg\mod\github.com\coreos\go-systemd\v22@v22.5.0\internal\dlopen`

It would be great to get this up and running for Windows computers as currently with Linux Triage packages I have look manually through them. This paired with specifying a root directory like chainsaw allows would allow for sigma rules to be ran on offline Linux machines instead of just live ones. 

Hopefully it is an easy fix as the tool seems exactly what I need

**Comment by M00NLIG7** [comment]
> When I attempt to build ChopChopGo for windows I get the following error: 
> 
> 
> 
> `github.com/coreos/go-systemd/v22/internal/dlopen: build constraints exclude all Go files in C:\Users\user\go\pkg\mod\github.com\coreos\go-systemd\v22@v22.5.0\internal\dlopen`
> 
> 
> 
> It would be great to get this up and running for Windows computers as currently with Linux Triage packages I have look manually through them. This paired with specifying a root directory like chainsaw allows would allow for sigma rules to be ran on offline Linux machines instead of just live ones. 
> 
> 
> 
> Hopefully it is an easy fix as the tool seems exactly what I need

I'll see what I can do!

**Comment by Herbert-Karl** [comment]
the error seems to be because the imported module `github.com/coreos/go-systemd/v22` uses C bindings, which apparently can't be cross-compiled.
So, in order to cross-compile, the "journald" part of ChopChopGo needs to be constrained such that it isn't considered when compiling for windows (probably with build constraints
