### ISSUE TITLE
The -file flag is not working for pre built ChopChopGo_v1.0.0-beta-3

### ISSUE THREAD

**Issue by tai5555** [M00NLIG7/ChopChopGo#13]
Can you please guide me how to run  it I am using the prebuilt ChopChopGo_v1.0.0-beta-3 and trying to scan a log file of a server on my PC but it gives an error that -file flag is not defined as shown in snap attached. Secondly I am not familiar with go so having an issue building it. Thanks
![chopchopgo_prebuilt_binary](https://github.com/M00NLIG7/ChopChopGo/assets/97503378/1cc750b9-82bc-4cad-b5eb-eeec0df7eb0d)
![error_in_building](https://github.com/M00NLIG7/ChopChopGo/assets/97503378/90565d1e-02e5-4005-915a-7a19c8d05ad9)

**Comment by M00NLIG7** [comment]
I will make sure to add a new release and some guidance on how to build later today when I get off of work sorry for the inconvenience

**Comment by M00NLIG7** [comment]
New release has been published. Also in the future when trying to compile ChopChopGo you can either use `go build -ldflags "-w" .` or use the Makefile with  `make generate` for linux or `make windows` for windows. Please confirm if this works for you!
