### ISSUE TITLE
Executing CHopChopGo against "dead" system

### ISSUE THREAD

**Issue by hodf-cye** [M00NLIG7/ChopChopGo#14]
Hey,
Is there a possibiliy to allow runing the tools against journal/logs that has been acquired from a different system?

**Comment by M00NLIG7** [comment]
Hello! Yes we do indeed support a -file option in ChopChopGo, which allows you to specify the source of your log files. If you have logs from a non-operational ('dead') machine, you can simply export these logs to a functioning machine. Once the logs are transferred, run ChopChopGo on the new machine and use the -file option to direct the program to the exported logs.

**Comment by hodf-cye** [comment]
Thanks for the quick response! I'll check that again..

**Comment by M00NLIG7** [comment]
I just published a new release including the -file option so you dont have to compile from source! Please confirm this meets your needs. If you have any ideas for a feature please feel free to make a request!

**Comment by hodf-cye** [comment]
Applogize for late response, we have managed to execute it against mounted FS.
Thanks!
