### ISSUE TITLE
Running ChopChopGo on windows 

### ISSUE THREAD

**Issue by jv2k4ever** [M00NLIG7/ChopChopGo#15]
Hi there, I am wondering how to go about running this on windows for linux logs Id like to review. Whenever I run the commands to scan this syslog file I get the window that I need to choose an app to load. 

Even the precompiled binaries when downloaded do not include an exe (./ChopChopGo.exe) so I'm wondering if I need to compile the binary on windows somehow. I checked the read me and all instructions appear to be for Linux only. Thank you for any and all assistance you may provide.

**Comment by M00NLIG7** [comment]
Thank you for bringing this to our attention. I apologize for any confusion, but I'd like to clarify that ChopChopGo does indeed support Windows. We have a windows option in our Makefile that compiles the executable for Windows systems.
I've personally tested running ChopChopGo on Windows without encountering any issues. However, I understand you may be experiencing problems. To help us investigate and resolve your specific issue could you please provide a screenshot of what's happening when you try to run ChopChopGo on your Windows system?

**Comment by jv2k4ever** [comment]
Hi thanks for the quick response. I saw that make file in the folder which Ill post a screenshot of. What is the command to compile the binary with makefile on windows? Attached is the screenshot of the folder when I unzip it with the blank files which I assume are linux files. (the syslog file in there is one that i moved over which i need to analyze)   
<img width="616" alt="image" src="https://github.com/user-attachments/assets/242db2a4-3628-4b7d-8b86-b629584a0df9">

im not sure if i need to install the linux subsystem on my windows machine (https://github.com/microsoft/WSL2-Linux-Kernel) or if this can be done with visual studio or something. any advice or recommendations you have would be appreciated.

**Comment by M00NLIG7** [comment]
the command would just be `make windows` assuming you have make and go installed. Here is the compiled x86_64 compiled version for windows if you just want to take it from me. I can update the release in a bit. 
[ChopChopGo_exe.zip](https://github.com/user-attachments/files/17282755/ChopChopGo_exe.zip) If you unzip and move the exe into the came folder as you screenshotted it should work fine.

**Comment by jv2k4ever** [comment]
Awesome, thank you so much. I'll play around with it and ensure go and make are installed. I went ahead and updated my ChopChop exe with the one you just sent and it looks like I'm very close however now getting this error , "Failed to parse events: open /var/log/messages: The system cannot find the path specified." 

<img width="853" alt="image" src="https://github.com/user-attachments/assets/547c2218-ea37-4fdd-9cec-82f3379bffa6">

I dropped the syslog file from the linux machines log directly onto my windows workstation directly into the Chop folder as seen in previous screenshot, so perhaps i need to compile the syslog to a windows format? not entirely sure.

**Comment by M00NLIG7** [comment]
By default ChopChopGo will search for logs in default locations. Specify the -file option if youd like to specify a target to run ChopChopGo against

**Comment by jv2k4ever** [comment]
Awesome thank you so much, I believe that did the trick (./ChopChopGo -file syslog -rules ./rules/linux/builtin/syslog/). If no results show does that mean that nothing was found?  
<img width="791" alt="image" src="https://github.com/user-attachments/assets/f5883997-2366-4e35-b1ca-fbfdaa0ce139">

**Comment by M00NLIG7** [comment]
Yeah that just means nothing matched the selected rules. But awesome! im glad that its running now!
