### ISSUE TITLE
CSV or JSON Output

### ISSUE THREAD

**Issue by weslambert** [M00NLIG7/ChopChopGo#2]
Thanks for all your work!

Would it be possible to provide CSV or JSON output, to make the output easier to parse?

**Comment by M00NLIG7** [comment]
> Thanks for all your work!
> 
> Would it be possible to provide CSV or JSON output, to make the output easier to parse?

Yes i will work on adding CSV and json ouput options asap

**Comment by M00NLIG7** [comment]
You can now output in JSON, CSV, or the original tables

**Comment by weslambert** [comment]
Thanks! I just tried with the following commands, but am not seeing the CSV or JSON output. 

`./ChopChopGo -target syslog -rules rules/linux/builtin/syslog/ -out csv`
`./ChopChopGo -target syslog -rules rules/linux/builtin/syslog/ -out json`

The regular table output works fine. 

`./ChopChopGo -target syslog -rules rules/linux/builtin/syslog/`
`./ChopChopGo -target syslog -rules rules/linux/builtin/syslog/ -out tables`

Would you be able to provide an example?

Also, it might be good to remove the header and progress bar and only have the data presented with the CSV and JSON options, to prevent issues with parsing stdout. Alternatively, an output file could be used to separate the data from the terminal output.

Thanks again for all of your help!

**Comment by weslambert** [comment]
During testing, I was able to change the underlying `./maps/syslog/syslog.go` file to print the results to stdout. I also modified it to print the other lines if the user selected the `tables` output or if no output was selected. I also updated `main.go` to only print the banner if `outputType` was not `csv` or `json`.

With that, I ended up with the following:

```
[
  {
    "message": "test-machine root: stopping iptables",
    "tags": [
      "attack.defense_evasion",
      "attack.t1562.004"
    ],
    "timestamp": "Mar  6 12:26:26"
  }
]
```

Snippet from `syslog.go` (`bar` has been removed from `csv` and `json` output types, as well as other default `fmt.Print()` statements)  
```
         if outputType == "json" {
                var jsonResults []map[string]interface{}
                for _, event := range events {
                        if result, match := ruleset.EvalAll(event); match {
                                results = append(results, result)
                                jsonResult := make(map[string]interface{})
                                jsonResult["timestamp"] = event.Timestamp
                                jsonResult["message"] = event.Message
                                jsonResult["tags"] = result[0].Tags
                                jsonResults = append(jsonResults, jsonResult)
                        }
                }

                jsonBytes, err := json.MarshalIndent(jsonResults, "", "  ")
                if err != nil {
                        log.Fatalf("Failed to marshal results to JSON: %v", err)
                }
                fmt.Print(string(jsonBytes))
                return string(jsonBytes)
        } else if outputType == "csv" {
                var csvResults [][]string
                for _, event := range events {
                        if result, match := ruleset.EvalAll(event); match {
                                results = append(results, result)
                                csvResult := []string{event.Timestamp, event.Message, strings.Join(result[0].Tags, "-")}
                                csvResults = append(csvResults, csvResult)
                        }
                }
                csvBytes := bytes.Buffer{}
                csvWriter := csv.NewWriter(&csvBytes)
                err := csvWriter.WriteAll(csvResults)
                if err != nil {
                        log.Fatalf("Failed to write CSV results: %v", err)
                }
                fmt.Print(csvBytes.String())
                return csvBytes.String()
        } else {
                fmt.Printf("Using syslog file: %s\n", syslogPath)
                table := tablewriter.NewWriter(os.Stdout)
                table.SetHeader([]string{"timestamp", "message", "tags"})
                for _, event := range events {
                        if result, match := ruleset.EvalAll(event); match {
                                results = append(results, result)
                                table.Append([]string{event.Timestamp, event.Message, strings.Join(result[0].Tags, "-")})
                        }
                        bar := progressbar.Default(int64(len(events)))
                        bar.Add(1)
                }
                fmt.Printf("Processed %d syslog events\n", len(events))
                table.Render()
                return results
        }

```

Snippet from `main.go`

```
        if(!((outputType == "csv") || (outputType == "json"))) {
            fmt.Println(banner)
        }
        switch target {
        case "auditd":
                auditd.Chop(path, outputType)
        case "syslog":
                syslog.Chop(path, outputType)
        case "journald":
                journald.Chop(path, outputType)
        default:
                fmt.Printf("Invalid Target Type")
                return
        }

```

I'm not sure if this is the best approach, but let me know your thoughts, and I can submit a pull request for your review, or if you are able to modify it, that would be great. Thanks!

**Comment by M00NLIG7** [comment]
> Thanks! I just tried with the following commands, but am not seeing the CSV or JSON output.
> 
> `./ChopChopGo -target syslog -rules rules/linux/builtin/syslog/ -out csv` `./ChopChopGo -target syslog -rules rules/linux/builtin/syslog/ -out json`
> 
> The regular table output works fine.
> 
> `./ChopChopGo -target syslog -rules rules/linux/builtin/syslog/` `./ChopChopGo -target syslog -rules rules/linux/builtin/syslog/ -out tables`
> 
> Would you be able to provide an example?
> 
> Also, it might be good to remove the header and progress bar and only have the data presented with the CSV and JSON options, to prevent issues with parsing stdout. Alternatively, an output file could be used to separate the data from the terminal output.
> 
> Thanks again for all of your help!

This is strange on my end this implementation works with the -out "type" format. Are you building from source or using the release?

**Comment by weslambert** [comment]
Hi! This was built from the updated source in the Github repo.

**Comment by M00NLIG7** [comment]
> Hi! This was built from the updated source in the Github repo.

interesting well I just committed you suggested changes + updated the csv to contain the header values. From my testing I did not run into any problems but it may be different for you

**Comment by weslambert** [comment]
Awesome, thanks! I'll test when I get a moment.

**Comment by weslambert** [comment]
The changes look good on my side 👍.

**Comment by weslambert** [comment]
I think the only thing left here would be to create a new release once the author and forked library reference changes are merged.

**Comment by M00NLIG7** [comment]
> I think the only thing left here would be to create a new release once the author and forked library reference changes are merged.

Coming up right now
