### ISSUE TITLE
Add Author Name to Results

### ISSUE THREAD

**Issue by weslambert** [M00NLIG7/ChopChopGo#3]
IIRC, the DRL, at least for the base Sigma repo, requests that the author's name be published for a Sigma rule match. Looking at the code, this doesn't seem too difficult to implement.

For example, here: https://github.com/M00NLIG7/ChopChopGo/blob/cb8a7a26acbadfcb9d67719d8b8ab308d2b3ce0a/maps/syslog/syslog.go#L129

 Would it be possible to add this functionality? I can also take a look at submitting a pull request.

Thanks!

**Comment by M00NLIG7** [comment]
The sigma module i am using to compare the rules doesnt return the author from the rules. If you can find a way around this let me know.

**Comment by weslambert** [comment]
I will take a look. Thanks!

**Comment by weslambert** [comment]
One option might be to switch to the following implementation.

https://github.com/bradleyjkemp/sigma-go

It seems like it might be more frequently updated upon briefly reviewing it.

**Comment by M00NLIG7** [comment]
Yeah I could try to move over to this library. This will take quite a bit more time than the other issues we have tackled so far though.

**Comment by weslambert** [comment]
No worries, I completely understand! I suppose another option would be to submit a pull request to the current library's repo to add the author to the result. I could also look at that as I get time.

**Comment by M00NLIG7** [comment]
> No worries, I completely understand! I suppose another option would be to submit a pull request to the current library's repo to add the author to the result. I could also look at that as I get time.

I will be making a PR to their repo, for now I will use my fork

**Comment by weslambert** [comment]
Sounds good!

**Comment by M00NLIG7** [comment]
Updated output with author name included has been included in the most recent commit as well as the reference to the forked version of go-sigma-rule-engine.

**Comment by weslambert** [comment]
Thanks! I also noticed the `Releases` page also shows `Release of Chainsaw v1 beta!`. Should this be `Release of ChopChopGo v1 beta!`?

**Comment by M00NLIG7** [comment]
> Thanks! I also noticed the `Releases` page also shows `Release of Chainsaw v1 beta!`. Should this be `Release of ChopChopGo v1 beta!`?

Yes i consider this the beta since there are still quite a few more SigmaRules i would like to add along with mappings. Also I need to do some more testing with more modified versions of syslog. This is just one component of an XDR me and my teammates at CSUSB are building for the Cyber Collegiate Defense Competition. We loved the tool Chainsaw but had no alternative for linux so i decided to take it into my own hands.

**Comment by weslambert** [comment]
Understood, sounds great! I too, am using this in conjunction with some other tools. I wasn't necessarily concerned with the `beta`, part, but more so the `Chainsaw` vs. `ChopChopGo` part. 

Looking at the output now, and to poke some more, would it be wise to include the rule ID or title as well? Now that the rule engine is forked, I would think it would be pretty straightforward to add more information by just adding the field via `tree.go` and `rule.go` . 

I can open additional issues for those different fields. Just let me know. Thanks!

**Comment by M00NLIG7** [comment]
Yes opening additional issues for any other features you think would be a good addition would be greatly appreciated. Also I  just realized it was a brain fart on my part haha must've overlooked naming thing
