### ISSUE TITLE
Add Sigma Rule ID and Title Fields to Output

### ISSUE THREAD

**Issue by weslambert** [M00NLIG7/ChopChopGo#4]
While we have a decent bit of information from the log message that was flagged, and some MITRE ATT&CK tags associated with each event, it would be nice to have the corresponding Sigma rule ID and title so that we can easily refer to which rules flagged particular events.

**Comment by M00NLIG7** [comment]
I'm all for this however, when outputting as a table this could start to look little weird. Should we just bear with it or do you think i should only add this extra info for csv and json output?

**Comment by weslambert** [comment]
Sure, maybe it could be specific to just csv and json output for now. Otherwise, it could be a global verbose option.

**Comment by M00NLIG7** [comment]
By the way the code for this is written but i am making some extra changes before I commit

**Comment by weslambert** [comment]
Awesome! Thanks for the heads up!

**Comment by M00NLIG7** [comment]
I have committed the changes you asked for!

**Comment by weslambert** [comment]
Thank you!  I just confirmed it's working as expected. Would it be possible to get a new release built?

**Comment by M00NLIG7** [comment]
Yes I can do that when I get a moment

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by weslambert** [comment]
Great, thanks!
