### ISSUE TITLE
go build is not working

### ISSUE THREAD

**Issue by hodf-cye** [M00NLIG7/ChopChopGo#5]
Hey,
I've tried to compile the code on several different kernel versions but I'm getting the same error again and again.
The error:
__/root/go/pkg/mod/github.com/mattn/go-runewidth@v0.0.14/runewidth.go:7:2: found packages uniseg (doc.go) and main (gen_breaktest.go) in /root/go/pkg/mod/github.com/rivo/uniseg@v0.4.3__

Is there anyone that expirienced similar issue?
Thanks

**Comment by weslambert** [comment]
What version of Go are you using?

Have you tried using the pre-compiled version of the binary instead?

**Comment by M00NLIG7** [comment]
Maybe try it with the updated make file

**Comment by hodf-cye** [comment]
Thank you for your quick response!
Problem has been solved by upgrading go and installing systemd-dev package (apt install libsystemd-dev)
I had to compile from source because the pre-compiled version has been compiled with new glibc version,
