### ISSUE TITLE
Target parameter

### ISSUE THREAD

**Issue by ghost** [M00NLIG7/ChopChopGo#7]
How I can use this tool with other sources, not from running system?
For example, if I have a sepatate log files from another system, can I check these files? What command I should use?

**Comment by M00NLIG7** [comment]
I can add an additional log_file parameter that will let you specify where you are pulling the log from. However, right now I only have mappings for syslog, auditd, and journald log types

**Comment by reece394** [comment]
This would be a great feature to add as currently you are not able to use a Linux triage package and use it with this tool like you can with chainsaw

**Comment by M00NLIG7** [comment]
File is now a new parameter as of commit [50ad7bf](https://github.com/M00NLIG7/ChopChopGo/commit/50ad7bf4d38be067bd26ec016bc4d3ba6225db6b)
